from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns=[
# url(r'^',views.homeApi),
url(r'^city$',views.CityApi),
url(r'^city/([a-zA-Z]+)',views.CityApi),
url(r'^airport$',views.AirportApi,name='airport'),
url(r'^airport/([a-zA-Z]+)',views.AirportApi),
url(r'^airline_code$',views.Airline_codeApi),
url(r'^airline_code/([a-zA-Z ]+)',views.Airline_codeApi),
url(r'^airline$',views.AirlineApi),
url(r'^airline/([a-zA-Z 0-9]+)',views.AirlineApi),
url(r'^connecting$',views.ConnectingApi),
url(r'^connecting/([a-zA-Z 0-9]+)',views.ConnectingApi),
url(r'^flights$',views.FlightsApi,name='flights'),
url(r'^flights/([a-zA-Z 0-9_]+)',views.FlightsApi),
url(r'^job_type$',views.Job_typeApi),
url(r'^job_type/([a-zA-Z 0-9_]+)',views.Job_typeApi),
url(r'^employees$',views.EmployeeApi),
url(r'^employees/([a-zA-Z 0-9_]+)',views.EmployeeApi),
url(r'^passengers$',views.PassengerApi),
url(r'^passengers/([a-zA-Z 0-9_]+)',views.PassengerApi),
url(r'^statezip$',views.State_zipApi),
url(r'^statezip/([a-zA-Z 0-9_]+)',views.State_zipApi),
url(r'^passengerdetails$',views.Pass_detailsApi),
url(r'^passengerdetails/([a-zA-Z 0-9_]+)',views.Pass_detailsApi),
url(r'^employeedetails$',views.Emp_detailsApi),
url(r'^employeedetails/([a-zA-Z 0-9_]+)',views.Emp_detailsApi),
url(r'^passengerphone$',views.Pass_phoneApi),
url(r'^passengerphone/([a-zA-Z 0-9_]+)',views.Pass_phoneApi),
url(r'^passemp$',views.Pass_phoneApi),
url(r'^passemp/([a-zA-Z 0-9_]+)',views.Pass_phoneApi),
url(r'^ticket$',views.TicketApi),
url(r'^ticket/([a-zA-Z 0-9_]+)',views.TicketApi),
url(r'^airportcity$',views.Airport_cityApi),
url(r'^airportcity/([a-zA-Z 0-9_]+)',views.Airport_cityApi),
url(r'^flightairport$',views.Flight_airApi),
url(r'^flightairport/([a-zA-Z 0-9_]+)',views.Flight_airApi),
url(r'^empphone$',views.Emp_phoneApi),
url(r'^empphone/([a-zA-Z 0-9_]+)',views.Emp_phoneApi),
]