# Generated by Django 3.2.8 on 2021-11-20 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_airline_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airline_code')),
            ],
        ),
    ]
