# Generated by Django 3.2.8 on 2021-11-20 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_airlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connecting',
            fields=[
                ('connection_ID', models.AutoField(primary_key=True, serialize=False)),
                ('layover_time', models.PositiveIntegerField()),
                ('airport_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airport')),
            ],
        ),
    ]
