# Generated by Django 3.2.8 on 2021-11-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_connecting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('time_at_source', models.DateTimeField()),
                ('time_at_destination', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('airline_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airlines')),
                ('connection_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.connecting')),
                ('source_airport_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airport')),
            ],
        ),
    ]
