# Generated by Django 3.2.8 on 2021-11-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_flights'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_type',
            fields=[
                ('job_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
