# Generated by Django 3.2.8 on 2021-11-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20211120_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('SSN', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('employee_ID', models.PositiveIntegerField()),
                ('joining_date', models.DateTimeField()),
                ('airport_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airport')),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job_type')),
            ],
        ),
    ]
