# Generated by Django 3.2.8 on 2021-11-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='SSN',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employee_ID',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
