# Generated by Django 3.2.8 on 2021-11-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211120_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passenger_ID', models.PositiveIntegerField()),
                ('passport_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('SSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
                ('flight_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flights')),
            ],
        ),
    ]
