# Generated by Django 3.2.8 on 2021-11-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengers',
            name='passenger_ID',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='passengers',
            name='passport_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
