# Generated by Django 3.2.8 on 2021-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211120_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_zipcode',
            fields=[
                ('zip_code', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
