# Generated by Django 3.2.8 on 2021-11-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_state_zipcode_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger_details',
            fields=[
                ('passport_number', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('zip_code', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
            ],
        ),
    ]
