# Generated by Django 3.2.8 on 2021-11-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_employee_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='SSN',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
