# Generated by Django 3.2.8 on 2021-11-21 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_passenger_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
                ('passport_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger_details')),
            ],
            options={
                'unique_together': {('passport_number', 'SSN')},
            },
        ),
    ]
