# Generated by Django 3.2.8 on 2021-11-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_passenger_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger_details',
            name='passport_number',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
