# Generated by Django 3.2.8 on 2021-11-21 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_passenger_details_passport_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_ID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('classes', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('date_of_travel', models.DateTimeField()),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('seat_number', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField()),
                ('cancellation_fee', models.PositiveIntegerField()),
                ('cancel_date', models.DateTimeField()),
                ('airline_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airlines')),
                ('flight_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flights')),
                ('passport_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.passenger_details')),
            ],
            options={
                'unique_together': {('passport_number', 'airline_ID', 'ticket_ID')},
            },
        ),
    ]
