# Generated by Django 3.2.8 on 2021-11-21 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_airport_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_iD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airport')),
                ('flight_iD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flights')),
            ],
            options={
                'unique_together': {('flight_iD', 'airport_iD')},
            },
        ),
    ]
