# Generated by Django 3.2.8 on 2021-11-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_flight_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_airport',
            name='airport_iD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.airport', unique=True),
        ),
        migrations.CreateModel(
            name='Employee_phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveIntegerField()),
                ('SSN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employees')),
            ],
            options={
                'unique_together': {('SSN', 'phone_number')},
            },
        ),
    ]
