# Generated by Django 3.2.8 on 2021-11-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20211120_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_phone',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='passenger_phone',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
